= Морфологічна розмітка
Данило Дубінін <danylo.dubinin@gmail.com>

Звіт індивідуального завдання 2015-16 навчального року.

[abstract]
== Огляд

Розглядаємо задачу морфологічної розмітки граматично побудованого речення
англійською мовою.

== Постановка задачі

Визначити частини мови слів речення англійською мовою.

== Частини мови

Для спрощення моделі використанні лише загальні типи частин мови:

ADJ ADP ADV CONJ DET NOUN NUM PRON PRT STOP VERB

Пунктуаційні знаки позначаються крапкою, а невідомі частини мови — X.

== Моделі Маркова

Моделі Маркова це стохастичні моделі, які застосовують у моделюванні систем, що
випадково змінюються, де передбачається, що майбутні стани залежать тільки від
поточного стану, і не від послідовності подій, які передували йому.<<1>> Як
правило, це припущення робить модель системи більш адекватною<<2>>(c.28).

Дискретний ланцюг Маркова можна представити як скінченний ймовірнісний
перетворювач<<3>>(Wighted automata).

=== Trigram Hidden Markov Models<<4>>

Our goal is to build a model whose input is a sentence. for example

the dog saw a cat

and whose output is a tag sequence, for example

D N V D N

We will use latexmath:[$x_1 \ldots  x_n$] to denote the input and $y_1 \ldots  y_n$ to
denote the output.

==== Model parameters

* tagset 
* known_words
* q
* e

[bibliography]
== Список літератури

[bibliography]
- [[[1]]] Сучасна теорія випадкових процесів // Ясинський. В.К. — Чернівці:
  Видавничий дім "Родовід", 2004. -292 с.
- [[[2]]] Математичне моделювання : навчальний посібник // Маценко В.Г. —
  Чернівці: Чернівецький національний університет, 2014. — 519 с.
- [[[3]]] https://en.wikipedia.org/wiki/Finite_state_transducer
- [[[4]]] Tagging Problems, and Hidden Markov Models - Columbia University
  http://www.cs.columbia.edu/~mcollins/hmms-spring2013.pdf
