= Морфологічна розмітка
Данило Дубінін <danylo.dubinin@gmail.com>
v0.1, 2015-12

Звіт індивідуального завдання з курсу «Випадкові процеси»

[abstract]
== Огляд

Розглядаємо задачу морфологічної розмітки граматично побудованого речення
англійською мовою.

== Постановка задачі

Визначити частини мови слів речення англійською мовою.

== Частини мови

Для спрощення моделі використанні лише загальні типи частин мови:
ADJ ADP ADV CONJ DET NOUN NUM PRON PRT STOP VERB
Пунктуаційні знаки позначаються як крапка, а невідомі частини мови — X.

== Моделі Маркова

Моделі Маркова це стохастичні моделі, які застосовують у моделювання систем, що
випадково змінюються, де передбачається, що майбутні стани залежать тільки від
поточного стану, і не від послідовності подій, які передували йому.<<1>> Як
правило, це припущення робить модель системи більш адекватною<<2>>(c.28).

Дискретний ланцюг Маркова можна представити як скінченний ймовірнісний
перетворювач<<3>>(Wighted automata).

Прихована модель Маркова

[bibliography]
== Список літератури

[bibliography]
- [[[1]]] Сучасна теорія випадкових процесів // Ясинський. В.К. — Чернівці:
  Видавничий дім "Родовід", 2004. -292 с.  
- [[[2]]] Математичне моделювання : навчальний посібник // Маценко В.Г. —
  Чернівці: Чернівецький національний університет, 2014. — 519 с.
- [[[3]]] https://en.wikipedia.org/wiki/Finite_state_transducer
